# Generated by Django 2.0.4 on 2018-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('q_dt', models.CharField(max_length=500)),
                ('a_dt', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('q_dt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Main_heading', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_url', models.CharField(default='/images/', max_length=100)),
                ('no_of_views', models.IntegerField(default=0)),
                ('no_of_posts', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
